name: Python CICD Kata
run-name: Python CICD Kata
on: [push]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "puproject.toml"
      - run: uv run ruff format .