name: Python CICD Kata Workflow
run-name: Run, build and deploy
on: [push]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Linter
        run: uv run ruff check .
      - name: Format
        run: uv run ruff format --check .
      - name: Type check
        run: uv run pyright
  tests:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: uv run pytest
  build:
    needs: tests
    runs-on: ubuntu-latest
    environment: poc
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: docker build -t jsvnext/python-cicd-kata:latest .
      - run: docker push jsvnext/python-cicd-kata:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: poc
    steps:
      - run: curl ${{ secrets.DEPLOY_WEBHOOK_URL }}
